version: '3'

services:
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: